const forgetPasswordText = "RESET YOUR PASSWORD BY USING THIS OTP CODE : "
const registrationText = "WELCOME TO THE FAMILY PLEASE ENTER THIS OTP TO CONTINUE YOUR REGISTRATION PROCESS : "
const loginOTPText = "PLEASE ENTER THIS OTP TO GET LOGGED IN  : "
const rejectionEmailText = "YOUR APPLICATION FOR REGISTRATION IN THE MENGAL KESHAV TRADING PLATFORM HAS BEEN REJECTED "
const accountFreezeEmailText = "YOUR ACCOUNT HAS BEEN FREEZED BY THE KESHA MENGAL KESHAV TRADING PLATFORM "
const accountActivationEmailText = "YOUR ACCOUNT HAS BEEN RE-ACTIVATED BY THE KESHA MENGAL KESHAV TRADING PLATFORM "
const removeUserEmailText = "YOUR MEMBERSHIP HAS BEEN CANCELLED BY THE MENGAL KESHAV PLATFORM .PLEASE REGISTER YOURSELF AGAIN TO BE MEMBER . THANKS "

export{
    forgetPasswordText,
    registrationText,
    loginOTPText,
    rejectionEmailText,
    accountFreezeEmailText,
    accountActivationEmailText
}